services:
  rdm-front:
    image: ${IMAGE}:${VERSION}
    container_name: rdm-front
    ports: 
      - "443:443"
    restart: always 
    volumes:
      - ./ssl/certificate.crt:/etc/ssl/certificate.crt
      - ./ssl/private.key:/etc/ssl/private.key
      - ./default.conf:/etc/nginx/conf.d/default.conf
