services:
  rdm-front:
    image: ${IMAGE}:${VERSION}
    container_name: rdm-front
    ports: 
      - "3080:3000"
    restart: always 
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rdm-network

networks:
  rdm-network:
    external: true