import type { ThemeDefinition } from "vuetify";

// export const staticPrimaryColor = "#1e40af";
export const staticPrimaryColor = "#0E76BC";
export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      primary: staticPrimaryColor,
      "on-primary": "#fff",
      "primary-darken-1": "#1e3a8a",
      "primary-darken-2": "#1e3a8a",
      "primary-lighten-1": "#ecf7ff",
      secondary: "#808390",
      "on-secondary": "#fff",
      "secondary-darken-1": "#737682",
      success: "#28C76F",
      "on-success": "#fff",
      "success-darken-1": "#24B364",
      info: "#00BAD1",
      "on-info": "#fff",
      "info-darken-1": "#00A7BC",
      warning: "#FF9F43",
      "on-warning": "#fff",
      "warning-darken-1": "#E68F3C",
      error: "#C61818",
      "on-error": "#fff",
      "error-darken-1": "#E64449",
      background: "#F8F7FA",
      "on-background": "#2F2B3D",
      surface: "#fff",
      "on-surface": "#2F2B3D",
      "grey-50": "#FAFAFA",
      "grey-100": "#F5F5F5",
      "grey-200": "#EEEEEE",
      "grey-300": "#E0E0E0",
      "grey-400": "#BDBDBD",
      "grey-500": "#9E9E9E",
      "grey-600": "#757575",
      "grey-700": "#616161",
      "grey-800": "#424242",
      "grey-900": "#212121",
      "grey-light": "#FAFAFA",
      "perfect-scrollbar-thumb": "#DBDADE",
      "skin-bordered-background": "#fff",
      "skin-bordered-surface": "#fff",
      "expansion-panel-text-custom-bg": "#fafafa",
    },
  },
};
